export enum STAT {
	HP = "HP",
	SHIELD = "SHIELD",
	EFFECT_MODIFIER = "EFFECT_MODIFIER",
	EFFECT_MULTIPLIER = "EFFECT_MULTIPLIER",
	COOLDOWN_MODIFIER = "COOLDOWN_MODIFIER",
	COOLDOWN_MULTIPLIER = "COOLDOWN_MULTIPLIER",
}
